#!/usr/bin/ruby
require 'json'
require 'net/http'
require 'uri'

uri = URI.parse("http://btc42.42.us.org/value.json\?user_token=omsay1k9XjQ248nMu2Pv")
values= JSON.parse(Net::HTTP.get(uri))

puts values

kind=""
if ARGV[0] == "sell"
    kind = "sell"
else
    kind = "buy"
end
urireturn = URI.parse("http://btc42.42.us.org/exchange")
btc_amount = ARGV[1]
user_input = {
    "user_token" => "omsay1k9XjQ248nMu2Pv",
    "btc_amount" => "#{btc_amount}",
    "kind" => "#{kind}"
}
Net::HTTP.post_form(urireturn, user_input)
values = JSON.parse(Net::HTTP.get(uri))
puts ("#{values["money_dollar"]} dollars")
puts ("#{values["money_btc"]} btc")